---
project_domain_name_servers: "{{ ansible_em1['ipv4'][0]['address'] }}"

project_subnets:
  - device: "{{ ansible_em1['device'] }}"
    ipv4:
      network:   "{{ ansible_em1['ipv4'][0]['network'] }}"
      broadcast: "{{ ansible_em1['ipv4'][0]['broadcast'] }}"
      netmask:   "{{ ansible_em1['ipv4'][0]['netmask'] }}"
    range_from: "{{ ansible_em1['ipv4'][0]['network'] | regex_replace('\\.\\d+$', '.100') }}"
    range_to:   "{{ ansible_em1['ipv4'][0]['network'] | regex_replace('\\.\\d+$', '.200') }}"
    routers:    "{{ ansible_em1['ipv4'][0]['address'] }}"

project_unbound_acl:
  - 0.0.0.0/0 refuse
  - ::0/0 refuse
  - 172.16.100.0/24 allow
  - 10.0.2.0/24 allow
  - 127.0.0.0/8 allow
  - ::1 allow

project_hosts:
  - name: fx230
    mac: 0:c0:c3:22:46:81
    ipv4: 192.168.1.3
  - name: ox230
    mac: 0:c0:c3:22:46:82
    ipv4: 192.168.1.4
