---
- name: trombik.localtime
  version: 1.1.0
- name: trombik.dhcpd_openbsd
  version: 2.0.0
- name: trombik.vim
  version: 1.1.2
- name: trombik.zsh
  version: 1.1.1
- name: trombik.hostname
  version: 1.0.1
- name: trombik.hosts
  version: 1.2.1
- name: trombik.git
  version: 1.1.2
- name: trombik.pf
  version: 1.1.0
- name: trombik.unbound
  version: 3.1.0
- name: trombik.resolver
  version: 2.2.0
