---
all:
  hosts:
    ns1.i.trombik.org:
      ansible_host: 192.168.11.254
      ansible_python_interpreter: /usr/local/bin/python2.7
  children:
    ns:
      hosts:
        ns1.i.trombik.org:
    prod-ns:
      children:
        ns:
    prod-credentials:
      children:
        ns:
    prod:
      children:
        ns:
