---
all:
  hosts:
    ns1.i.trombik.org:
      ansible_host: 192.168.99.251
      ansible_python_interpreter: /usr/local/bin/python3
      vars:
        ansible_python_interpreter: /usr/local/bin/python3
  children:
    ns:
      hosts:
        ns1.i.trombik.org:
    prod-ns:
      children:
        ns:
    prod-credentials:
      children:
        ns:
    prod:
      children:
        ns:
